"""
Shared string enums for the Catering Outreach Platform.

Using str-based enums ensures they are JSON-serializable, work directly
with SQLAlchemy String columns, and are accepted by Pydantic v2 fields
without any adapter — all values are stored as plain strings in the DB.
"""
from enum import Enum


class LeadStatus(str, Enum):
    """
    Unified lifecycle status for a Lead.
    Replaces the fragmented status/review_status/is_qualified pattern.
    """
    DISCOVERED = "DISCOVERED"          # Fresh from Apify, not yet evaluated
    QUALIFIED = "QUALIFIED"            # Passed qualification scoring (score ≥ 70)
    REVIEW_REQUIRED = "REVIEW_REQUIRED"  # Borderline score (40–69), needs human review
    CONTACTED = "CONTACTED"            # First outreach email sent
    INTERESTED = "INTERESTED"          # Lead responded positively
    MEETING_REQUESTED = "MEETING_REQUESTED"  # Meeting / tasting scheduled
    BOOKED = "BOOKED"                  # Booking confirmed
    CLOSED_WON = "CLOSED_WON"         # Successfully converted to client
    CLOSED_LOST = "CLOSED_LOST"        # Lost — not interested
    REJECTED = "REJECTED"              # Failed qualification (score < 40) or bad data


class CampaignStatus(str, Enum):
    """Lifecycle status for an outreach campaign."""
    DRAFT = "draft"
    ACTIVE = "active"
    PAUSED = "paused"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class MessageStatus(str, Enum):
    """
    Lifecycle status for a generated outreach message.
    Tracks the full flow from AI generation through to delivery.
    """
    DRAFT = "draft"          # Manually created, not yet AI-generated
    GENERATED = "generated"  # Just generated by AI, pending review
    EDITED = "edited"        # Human-edited after generation
    APPROVED = "approved"    # Approved for sending
    SENT = "sent"            # Dispatched via SendGrid (future)
    FAILED = "failed"        # Send attempt failed
    REPLIED = "replied"      # Lead responded to this specific message
