"""Add LeadCampaignAssignment

Revision ID: 12cac90ab4e3
Revises: 31657956de04
Create Date: 2026-06-04 12:25:51.118045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12cac90ab4e3'
down_revision: Union[str, None] = '31657956de04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_campaign_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_campaign_assignments_campaign_id'), 'lead_campaign_assignments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_campaign_assignments_id'), 'lead_campaign_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_lead_campaign_assignments_lead_id'), 'lead_campaign_assignments', ['lead_id'], unique=False)
    op.drop_index(op.f('ix_campaign_settings_campaign_id'), table_name='campaign_settings')
    op.drop_index(op.f('ix_campaign_settings_id'), table_name='campaign_settings')
    op.drop_table('campaign_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_settings',
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('restaurant_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sender_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reply_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('offer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('call_to_action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('brand_voice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name=op.f('campaign_settings_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('campaign_settings_pkey'))
    )
    op.create_index(op.f('ix_campaign_settings_id'), 'campaign_settings', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_settings_campaign_id'), 'campaign_settings', ['campaign_id'], unique=True)
    op.drop_index(op.f('ix_lead_campaign_assignments_lead_id'), table_name='lead_campaign_assignments')
    op.drop_index(op.f('ix_lead_campaign_assignments_id'), table_name='lead_campaign_assignments')
    op.drop_index(op.f('ix_lead_campaign_assignments_campaign_id'), table_name='lead_campaign_assignments')
    op.drop_table('lead_campaign_assignments')
    # ### end Alembic commands ###
