"""Add campaigns campaign_settings lead_outreach_messages tables

Revision ID: 1fc310d6abb8
Revises: baecc2703398
Create Date: 2026-06-03 05:30:33.936674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc310d6abb8'
down_revision: Union[str, None] = 'baecc2703398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=False),
    sa.Column('target_business_type', sa.String(length=255), nullable=False),
    sa.Column('offer', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_campaign_type'), 'campaign', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_target_business_type'), 'campaign', ['target_business_type'], unique=False)
    op.create_table('campaign_settings',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=255), nullable=False),
    sa.Column('restaurant_location', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('reply_email', sa.String(length=255), nullable=False),
    sa.Column('offer', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_settings_campaign_id'), 'campaign_settings', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_campaign_settings_id'), 'campaign_settings', ['id'], unique=False)
    op.create_table('lead_outreach_message',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_outreach_message_campaign_id'), 'lead_outreach_message', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_lead_outreach_message_id'), 'lead_outreach_message', ['id'], unique=False)
    op.create_index(op.f('ix_lead_outreach_message_lead_id'), 'lead_outreach_message', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_outreach_message_message_type'), 'lead_outreach_message', ['message_type'], unique=False)
    op.create_index(op.f('ix_lead_outreach_message_status'), 'lead_outreach_message', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_outreach_message_status'), table_name='lead_outreach_message')
    op.drop_index(op.f('ix_lead_outreach_message_message_type'), table_name='lead_outreach_message')
    op.drop_index(op.f('ix_lead_outreach_message_lead_id'), table_name='lead_outreach_message')
    op.drop_index(op.f('ix_lead_outreach_message_id'), table_name='lead_outreach_message')
    op.drop_index(op.f('ix_lead_outreach_message_campaign_id'), table_name='lead_outreach_message')
    op.drop_table('lead_outreach_message')
    op.drop_index(op.f('ix_campaign_settings_id'), table_name='campaign_settings')
    op.drop_index(op.f('ix_campaign_settings_campaign_id'), table_name='campaign_settings')
    op.drop_table('campaign_settings')
    op.drop_index(op.f('ix_campaign_target_business_type'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_campaign_type'), table_name='campaign')
    op.drop_table('campaign')
    # ### end Alembic commands ###
