"""Add platform_settings brand_voice normalize lead status

Revision ID: 31657956de04
Revises: 1fc310d6abb8
Create Date: 2026-06-03 06:25:48.068247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31657956de04'
down_revision: Union[str, None] = '1fc310d6abb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('restaurant_name', sa.String(length=255), nullable=False),
    sa.Column('restaurant_location', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('reply_email', sa.String(length=255), nullable=False),
    sa.Column('offer', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('brand_voice', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.add_column('campaign_settings', sa.Column('brand_voice', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Data migration: normalize all existing lead.status values to the canonical
    # LeadStatus enum (uppercase).  Old free-text values are mapped to their
    # closest semantic equivalent so no existing data is lost.
    # -------------------------------------------------------------------------
    op.execute("""
        UPDATE lead SET status = CASE
            WHEN status = 'discovered'        THEN 'DISCOVERED'
            WHEN status = 'contacted'         THEN 'CONTACTED'
            WHEN status = 'replied'           THEN 'INTERESTED'
            WHEN status = 'interested'        THEN 'INTERESTED'
            WHEN status = 'meeting_requested' THEN 'MEETING_REQUESTED'
            WHEN status = 'in_pipeline'       THEN 'CONTACTED'
            WHEN status = 'booked'            THEN 'BOOKED'
            WHEN status = 'converted'         THEN 'CLOSED_WON'
            WHEN status = 'closed_won'        THEN 'CLOSED_WON'
            WHEN status = 'closed_lost'       THEN 'CLOSED_LOST'
            WHEN status = 'ignored'           THEN 'REJECTED'
            WHEN status = 'rejected'          THEN 'REJECTED'
            WHEN status = 'qualified'         THEN 'QUALIFIED'
            WHEN status = 'needs_review'      THEN 'REVIEW_REQUIRED'
            WHEN status = 'DISCOVERED'        THEN 'DISCOVERED'
            WHEN status = 'QUALIFIED'         THEN 'QUALIFIED'
            WHEN status = 'REVIEW_REQUIRED'   THEN 'REVIEW_REQUIRED'
            WHEN status = 'CONTACTED'         THEN 'CONTACTED'
            WHEN status = 'INTERESTED'        THEN 'INTERESTED'
            WHEN status = 'MEETING_REQUESTED' THEN 'MEETING_REQUESTED'
            WHEN status = 'BOOKED'            THEN 'BOOKED'
            WHEN status = 'CLOSED_WON'        THEN 'CLOSED_WON'
            WHEN status = 'CLOSED_LOST'       THEN 'CLOSED_LOST'
            WHEN status = 'REJECTED'          THEN 'REJECTED'
            ELSE 'DISCOVERED'
        END
        WHERE status IS NOT NULL
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign_settings', 'brand_voice')
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
