"""Add lead qualification and cleanup fields

Revision ID: baecc2703398
Revises: fdd6667c4f63
Create Date: 2026-06-01 06:57:39.985643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baecc2703398'
down_revision: Union[str, None] = 'fdd6667c4f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('lead_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('lead', sa.Column('is_qualified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('lead', sa.Column('qualification_reason', sa.Text(), nullable=True))
    op.add_column('lead', sa.Column('cleaned_email', sa.Text(), nullable=True))
    op.add_column('lead', sa.Column('cleaned_website', sa.Text(), nullable=True))
    op.add_column('lead', sa.Column('cleaned_phone', sa.Text(), nullable=True))
    op.add_column('lead', sa.Column('review_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_lead_review_status'), 'lead', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_review_status'), table_name='lead')
    op.drop_column('lead', 'review_status')
    op.drop_column('lead', 'cleaned_phone')
    op.drop_column('lead', 'cleaned_website')
    op.drop_column('lead', 'cleaned_email')
    op.drop_column('lead', 'qualification_reason')
    op.drop_column('lead', 'is_qualified')
    op.drop_column('lead', 'lead_score')
    # ### end Alembic commands ###
